/* Nombres en español de las divisas que sirve Frankfurter en /v2/currencies.
   Se mantienen aquí en vez de pedirlos a la API porque esta los devuelve en
   inglés. El código ISO se muestra siempre junto al nombre, así que la moneda
   queda identificada aunque la traducción no sea la de uso local. */

export const CURRENCIES: Record<string, string> = {
  AED: "Dírham de Emiratos Árabes Unidos",
  AFN: "Afgani afgano",
  ALL: "Lek albanés",
  AMD: "Dram armenio",
  ANG: "Florín de las Antillas Neerlandesas",
  AOA: "Kwanza angoleño",
  ARS: "Peso argentino",
  AUD: "Dólar australiano",
  AWG: "Florín arubeño",
  AZN: "Manat azerbaiyano",
  BAM: "Marco convertible de Bosnia y Herzegovina",
  BBD: "Dólar de Barbados",
  BDT: "Taka bangladesí",
  BHD: "Dinar bareiní",
  BIF: "Franco de Burundi",
  BMD: "Dólar bermudeño",
  BND: "Dólar de Brunéi",
  BOB: "Boliviano",
  BRL: "Real brasileño",
  BSD: "Dólar bahameño",
  BTN: "Ngultrum butanés",
  BWP: "Pula de Botsuana",
  BYN: "Rublo bielorruso",
  BZD: "Dólar beliceño",
  CAD: "Dólar canadiense",
  CDF: "Franco congoleño",
  CHF: "Franco suizo",
  CLP: "Peso chileno",
  CNH: "Yuan chino (extraterritorial)",
  CNY: "Yuan chino",
  COP: "Peso colombiano",
  CRC: "Colón costarricense",
  CUP: "Peso cubano",
  CVE: "Escudo caboverdiano",
  CZK: "Corona checa",
  DJF: "Franco yibutiano",
  DKK: "Corona danesa",
  DOP: "Peso dominicano",
  DZD: "Dinar argelino",
  EGP: "Libra egipcia",
  ERN: "Nakfa eritreo",
  ETB: "Birr etíope",
  EUR: "Euro",
  FJD: "Dólar fiyiano",
  FKP: "Libra malvinense",
  GBP: "Libra esterlina",
  GEL: "Lari georgiano",
  GGP: "Libra de Guernesey",
  GHS: "Cedi ghanés",
  GIP: "Libra de Gibraltar",
  GMD: "Dalasi gambiano",
  GNF: "Franco guineano",
  GTQ: "Quetzal guatemalteco",
  GYD: "Dólar guyanés",
  HKD: "Dólar de Hong Kong",
  HNL: "Lempira hondureño",
  HTG: "Gourde haitiano",
  HUF: "Forinto húngaro",
  IDR: "Rupia indonesia",
  ILS: "Nuevo séquel israelí",
  IMP: "Libra de la Isla de Man",
  INR: "Rupia india",
  IQD: "Dinar iraquí",
  IRR: "Rial iraní",
  ISK: "Corona islandesa",
  JEP: "Libra de Jersey",
  JMD: "Dólar jamaicano",
  JOD: "Dinar jordano",
  JPY: "Yen japonés",
  KES: "Chelín keniano",
  KGS: "Som kirguís",
  KHR: "Riel camboyano",
  KMF: "Franco comorense",
  KPW: "Won norcoreano",
  KRW: "Won surcoreano",
  KWD: "Dinar kuwaití",
  KYD: "Dólar de las Islas Caimán",
  KZT: "Tenge kazajo",
  LAK: "Kip laosiano",
  LBP: "Libra libanesa",
  LKR: "Rupia de Sri Lanka",
  LRD: "Dólar liberiano",
  LSL: "Loti lesotense",
  LYD: "Dinar libio",
  MAD: "Dírham marroquí",
  MDL: "Leu moldavo",
  MGA: "Ariary malgache",
  MKD: "Denar macedonio",
  MMK: "Kyat birmano",
  MNT: "Tugrik mongol",
  MOP: "Pataca macaense",
  MRO: "Uguiya mauritana (antigua)",
  MRU: "Uguiya mauritana",
  MUR: "Rupia mauriciana",
  MVR: "Rufiyaa maldiva",
  MWK: "Kwacha malauí",
  MXN: "Peso mexicano",
  MYR: "Ringgit malayo",
  MZN: "Metical mozambiqueño",
  NAD: "Dólar namibio",
  NGN: "Naira nigeriana",
  NIO: "Córdoba nicaragüense",
  NOK: "Corona noruega",
  NPR: "Rupia nepalí",
  NZD: "Dólar neozelandés",
  OMR: "Rial omaní",
  PAB: "Balboa panameño",
  PEN: "Sol peruano",
  PGK: "Kina de Papúa Nueva Guinea",
  PHP: "Peso filipino",
  PKR: "Rupia pakistaní",
  PLN: "Esloti polaco",
  PYG: "Guaraní paraguayo",
  QAR: "Riyal catarí",
  RON: "Leu rumano",
  RSD: "Dinar serbio",
  RUB: "Rublo ruso",
  RWF: "Franco ruandés",
  SAR: "Riyal saudí",
  SBD: "Dólar de las Islas Salomón",
  SCR: "Rupia seychelense",
  SDG: "Libra sudanesa",
  SEK: "Corona sueca",
  SGD: "Dólar de Singapur",
  SHP: "Libra de Santa Elena",
  SLE: "Nuevo leone",
  SOS: "Chelín somalí",
  SRD: "Dólar surinamés",
  SSP: "Libra sursudanesa",
  STN: "Dobra santotomense",
  SVC: "Colón salvadoreño",
  SYP: "Libra siria",
  SZL: "Lilangeni suazi",
  THB: "Baht tailandés",
  TJS: "Somoni tayiko",
  TMT: "Manat turcomano",
  TND: "Dinar tunecino",
  TOP: "Paanga tongano",
  TRY: "Lira turca",
  TTD: "Dólar de Trinidad y Tobago",
  TWD: "Nuevo dólar taiwanés",
  TZS: "Chelín tanzano",
  UAH: "Grivna ucraniana",
  UGX: "Chelín ugandés",
  USD: "Dólar estadounidense",
  UYU: "Peso uruguayo",
  UZS: "Som uzbeko",
  VES: "Bolívar soberano venezolano",
  VND: "Dong vietnamita",
  VUV: "Vatu vanuatuense",
  WST: "Tala samoano",
  XAF: "Franco CFA de África Central",
  XAG: "Plata (onza troy)",
  XAU: "Oro (onza troy)",
  XCD: "Dólar del Caribe Oriental",
  XCG: "Florín caribeño",
  XDR: "Derechos especiales de giro (FMI)",
  XOF: "Franco CFA de África Occidental",
  XPD: "Paladio (onza troy)",
  XPF: "Franco CFP",
  XPT: "Platino (onza troy)",
  YER: "Rial yemení",
  ZAR: "Rand sudafricano",
  ZMW: "Kwacha zambiano",
  ZWG: "Zimbabue Gold",
};

/* Las 30 divisas de referencia del Banco Central Europeo. Son las únicas que
   sirve /v1, que es el endpoint con series temporales, así que la gráfica
   histórica solo puede dibujarse cuando ambas monedas del par están aquí. */
export const ECB_CURRENCIES = new Set([
  "AUD", "BRL", "CAD", "CHF", "CNY", "CZK", "DKK", "EUR", "GBP", "HKD",
  "HUF", "IDR", "ILS", "INR", "ISK", "JPY", "KRW", "MXN", "MYR", "NOK",
  "NZD", "PHP", "PLN", "RON", "SEK", "SGD", "THB", "TRY", "USD", "ZAR",
]);

export const CURRENCY_CODES = Object.keys(CURRENCIES).sort();
